ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'MANUAL_REVIEW';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'REFUND_PENDING';

ALTER TYPE "PaymentStatus" ADD VALUE IF NOT EXISTS 'CREATED';
ALTER TYPE "PaymentStatus" ADD VALUE IF NOT EXISTS 'EXPIRED';
ALTER TYPE "PaymentStatus" ADD VALUE IF NOT EXISTS 'UNKNOWN';
ALTER TYPE "PaymentStatus" ADD VALUE IF NOT EXISTS 'REFUND_PENDING';
ALTER TYPE "PaymentStatus" ADD VALUE IF NOT EXISTS 'REFUND_FAILED';

ALTER TYPE "DeliveryStatus" ADD VALUE IF NOT EXISTS 'QUEUED';
ALTER TYPE "DeliveryStatus" ADD VALUE IF NOT EXISTS 'PROVIDER_PENDING';
ALTER TYPE "DeliveryStatus" ADD VALUE IF NOT EXISTS 'FAILED_RETRYABLE';
ALTER TYPE "DeliveryStatus" ADD VALUE IF NOT EXISTS 'FAILED_FINAL';
ALTER TYPE "DeliveryStatus" ADD VALUE IF NOT EXISTS 'MANUAL_REVIEW';
